name: Tuotanto Tests
on:
  workflow_dispatch:
  schedule:
     - cron:  '30 7 * * 1-5'
env:
  SLACK_TOKEN: ${{ secrets.VALVONTA_TUOTANTO_SLACK_TOKEN }}
  REPORT_DOMAIN: Tuotanto
  ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      id: run-prod-tests
      continue-on-error: true
      run: npm run test:prod
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 4
    - name: Send failure message
      if: failure() && steps.run-prod-tests.outcome == 'failure'
      run: ./slack_notify.sh